name: Rust

on:
  push:
    branches: [ master, developer ]
  pull_request:
    branches: [ master, developer ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare bevy essentials
      run: sudo apt-get install librust-alsa-sys-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
